name: Update Models Manual
on:
  workflow_dispatch:
    inputs:
      models_path:
        type: string
        required: true
      framework:
        type: string
        required: true

jobs:
  update-models:
    uses: supervisely-ecosystem/workflows/.github/workflows/update_models_common.yml@master
    with:
      MODELS_PATH: models/models.json
      FRAMEWORK: SparseInst
      SERVER_ADDRESS: ${{ vars.SUPERVISELY_PROD_SERVER_ADDRESS }}
    secrets:
      API_TOKEN: ${{ secrets.SUPERVISELY_PROD_API_TOKEN }}